name: pasada_admin_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  desktop_webview_window: ^0.2.3
  supabase_flutter: ^2.8.4
  connectivity_plus: ^6.1.3
  supabase: ^2.6.3
  google_maps_flutter: ^2.12.1
  google_maps_flutter_web: ^0.5.12
  uuid: ^4.5.1
  cupertino_icons: ^1.0.8
  flutter_animate: ^4.5.2
  flutter_svg: ^2.0.17
  geolocator: ^14.0.0
  geocoding: ^4.0.0
  flutter_typeahead: ^5.2.0
  location: ^8.0.0
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.5.0
  webview_flutter_wkwebview: ^3.21.0
  h3_flutter: ^0.7.0
  dio: ^5.8.0+1
  get: ^4.7.2
  flutter_google_maps_webservices: ^1.1.1
  flutter_polyline_points: ^3.0.1
  http: ^1.3.0
  sqflite: ^2.4.2
  flutter_heatmap_calendar: ^1.0.5
  intl: ^0.20.2
  image_picker: ^1.1.2
  bcrypt: ^1.1.3
  shared_preferences: ^2.5.3
  provider: ^6.1.2
  flutter_gemini: ^3.0.0
  gemini_ai: ^1.0.1
  fluttertoast: ^8.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/.env
    - assets/novadeci.png
    - assets/pasadaAppIcon.png
    - assets/pasadaLogoUpdated.png
    - assets/pasadaLogoUpdated_Black.png
    - assets/PasadaLogoWithoutText.png
    - assets/pinIdling.png
    - assets/pinOnline.png
    - assets/pinOffline.png
    - assets/web/map.html
    - assets/web/map.js

fonts:
  - family: Inter
    fonts:
      - asset: fonts/Inter_18pt-Black.ttf
        weight: 900
      - asset: fonts/Inter_18pt-BlackItalic.ttf
        weight: 900
        style: italic
      - asset: fonts/Inter_18pt-Bold.ttf
        weight: 700
      - asset: fonts/Inter_18pt-BoldItalic.ttf
        weight: 700
        style: italic
      - asset: fonts/Inter_18pt-Regular.ttf
        weight: 400
      - asset: fonts/Inter_18pt-Italic.ttf
        weight: 400
        style: italic
      - asset: fonts/Inter_18pt-Light.ttf
        weight: 300
      - asset: fonts/Inter_18pt-LightItalic.ttf
        weight: 300
        style: italic
      - asset: fonts/Inter_24pt-Bold.ttf
        weight: 700
      - asset: fonts/Inter_24pt-Regular.ttf
        weight: 400
      - asset: fonts/Inter_28pt-Bold.ttf
        weight: 700
      - asset: fonts/Inter_28pt-Regular.ttf
        weight: 400