name: pasada_admin_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
fonts:
  - family: Inter
    fonts:
      - asset: fonts/Inter_18pt-Black.ttf
        weight: 900
      - asset: fonts/Inter_18pt-BlackItalic.ttf
        weight: 900
        style: italic
      - asset: fonts/Inter_18pt-Bold.ttf
        weight: 700
      - asset: fonts/Inter_18pt-BoldItalic.ttf
        weight: 700
        style: italic
      - asset: fonts/Inter_18pt-Regular.ttf
        weight: 400
      - asset: fonts/Inter_18pt-Italic.ttf
        weight: 400
        style: italic
      - asset: fonts/Inter_18pt-Light.ttf
        weight: 300
      - asset: fonts/Inter_18pt-LightItalic.ttf
        weight: 300
        style: italic
      - asset: fonts/Inter_24pt-Bold.ttf
        weight: 700
      - asset: fonts/Inter_24pt-Regular.ttf
        weight: 400
      - asset: fonts/Inter_28pt-Bold.ttf
        weight: 700
      - asset: fonts/Inter_28pt-Regular.ttf
        weight: 400